   # webserver/tasks/main.yml
- name: Install nginx package
  ansible.builtin.package:
    name: "{{ webserver }}"
    state: present

- name: Create directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: nginx
    group: nginx
    mode: '0755'
  loop: "{{ directories }}"

- name: Template nginx configuration
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify: Restart nginx

