   # tasks/main.yml
   - name: Install nginx package
     package:
       name: "{{ webserver }}"
       state: present

   - name: Template the nginx.conf file
     template:
       src: nginx.conf.j2
       dest: /etc/nginx/nginx.conf
     notify: Restart nginx package
   